---
- name: Include apache config vars
  include_vars:
    file: "{{ item }}"
  with_items:
    - vars/configs/apache.yml
    - vars/configs/apache_maintenance.yml
    - vars/condigs/ssl_certs.yml

- name: Edit apache mpm config
  replace:
    path: /etc/apache2/mods-enabled/mpm_event.conf
    regexp: '(<IfModule mpm_event_module>[\s\S]*)</IfModule>'
    replace: |
      {{ apache_mpm_config }}
  when: server_name == "gate" or server_name == "neo_us" or server_name == "neo_uk" or server_name == "sso_us" or server_name == "sso_uk"

- name: Create apache common config file
  blockinfile:
    dest: /etc/apache2/conf-available/passenger-common.conf
    create: yes
    owner: root
    group: root
    mode: 0644
    block: |
      <IfModule mod_passenger.c>
        PassengerMaxPoolSize 70
        PassengerPoolIdleTime 0
        PassengerMinInstances 70
      </IfModule>
  when: server_name == "neo_us" or server_name == "neo_uk"

- name: Enable passenger-common config
  shell: a2enconf passenger-common
  when: server_name == "neo_us" or server_name == "neo_uk"

- name: Create common and ssl directories
  file:
    dest: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - /etc/apache2/ssl
    - /etc/apache2/common

- name: Create apache maintenance file
  blockinfile:
    dest: /etc/apache2/common/apache.maintenance
    create: yes
    mode: 0644
    block: |
      {{ apache_maintenance }}

- name: Create apache disabled maintenance file
  blockinfile:
    dest: /etc/apache2/common/maintenance.html.disabled
    create: yes
    mode: 0644
    block: |
      {{ apache_maintenance_disabled }}

- name: Create common ssl file
  blockinfile:
    dest: /etc/apache2/common/{{ app_name }}.{{ app_env }}.ssl
    create: yes
    mode: 0644
    block: |
      SSLEngine on
      SSLCertificateFile   /etc/apache2/ssl/{{ app_env }}.crt
      SSLCertificateKeyFile /etc/apache2/ssl/{{ app_env }}.key
      SSLCertificateChainFile /etc/apache2/ssl/gd_bundle_{{ app_env }}.crt

- name: Create gd_bundle ssl key
  blockinfile:
    dest: /etc/apache2/ssl/gd_bundle_{{ app_env }}.crt
    create: yes
    mode: 0644
    block: |
      {{ gd_bundle }}

- name: Create ssl crt
  blockinfile:
    dest: /etc/apache2/ssl/{{ app_env }}.crt
    create: yes
    mode: 0644
    block: |
      {{ ssl_crt }}

- name: Create ssl key
  blockinfile:
    dest: /etc/apache2/ssl/{{ app_env }}.key
    create: yes
    mode: 0644
    block: |
      {{ ssl_key }}

- name: Enable rewrite module
  apache2_module:
    name: rewrite
    state: present

- name: Enable headers module
  apache2_module:
    name: headers
    state: present
  when: server_name == "neo" or "neoapp"

- name: Enable expires module
  apache2_module:
    name: expires
    state: present
  when: server_name == "neo" or "neoapp"

- name: Disable default site
  shell: a2dissite 000-default

- name: Change permissions of apache log dir
  file:
    dest: /var/log/apache2
    state: directory
    mode: 0755
